### ISSUE TITLE
Первоначальный коммит, не выполняется с ошибкой

### ISSUE THREAD

**Issue by Caponid** [bia-technologies/precommit4onec#1]
$ git commit -m "initial commit"
precommit4onec v1.10.0
11.06.2019 12:11:05: ИНФОРМАЦИЯ - Используем глобальные настройки
11.06.2019 12:11:05: ИНФОРМАЦИЯ - Читаем настройки
ОШИБКА - Получен ненулевой код возврата 128. Выполнение скрипта остановлено!
11.06.2019 12:11:06: КРИТИЧНАЯОШИБКА - {Модуль C:\OneScript\lib\gitrunner\src\ГитРепозиторий.os / Ошибка в строке: 868 / fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'}
            ВызватьИсключение ПолучитьВыводКоманды();

**Comment by theshadowco** [comment]
Это для только что созданного репозитория? Учтем в следующем релизе

**Comment by Caponid** [comment]
да, чистый репозиторий.
а вот в SourceTree ошибка та же, но в другом месте..
git -c diff.mnemonicprefix=false -c core.quotepath=false --no-optional-locks commit -v -q -F C:\Users\*******\AppData\Local\Temp\6\jln32s4f.3q0
precommit4onec v1.10.0
11.06.2019 13:20:13: ИНФОРМАЦИЯ - Используем глобальные настройки
11.06.2019 13:20:13: ИНФОРМАЦИЯ - Читаем настройки
11.06.2019 13:20:13: КРИТИЧНАЯОШИБКА - {Модуль C:\OneScript\lib\1commands\src\Команда.os / Ошибка в строке: 310 / Внешнее исключение (System.ArgumentException): Элемент уже добавлен. Ключ в словаре: "HOME"  Добавляемый ключ: 'home'}    
		Процесс = СоздатьПроцесс(СтрокаЗапуска, РабочийКаталог, ПерехватыватьПотоки, ПерехватыватьПотоки, КодировкаВывода, ПеременныеСреды());

**Comment by Caponid** [comment]
а как обойти? хочется попробовать, но не получается....

**Comment by theshadowco** [comment]
SourceTree вообще плохо работает с прекоммит хуками. Судя по ошибке, проблема может быть в 1commands. попробуй другую версию поставить

**Comment by theshadowco** [comment]
если чистый реп, то надо сначала сделать один коммит (init, например readme). Потом подключить прекоммит  коммитить что нада

**Comment by Caponid** [comment]
спс, получилось.

**Comment by theshadowco** [comment]
Исправлено в https://github.com/bia-technologies/precommit4onec/releases/tag/1.11
