### ISSUE TITLE
Смена каталога назначения

### ISSUE THREAD

**Issue by Live-AG** [bia-technologies/precommit4onec#11]
Из описания сценария [РазборОтчетОбработокРасширений](https://github.com/bia-technologies/precommit4onec/blob/master/docs/%D0%A0%D0%B0%D0%B7%D0%B1%D0%BE%D1%80%D0%9E%D1%82%D1%87%D0%B5%D1%82%D0%9E%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BE%D0%BA%D0%A0%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D0%B9.md#%D1%81%D1%86%D0%B5%D0%BD%D0%B0%D1%80%D0%B8%D0%B9-%D1%80%D0%B0%D0%B7%D0%B1%D0%BE%D1%80%D0%BE%D1%82%D1%87%D0%B5%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BE%D0%BA%D1%80%D0%B0%D1%81%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D0%B8%D0%B9):
> Полученные исходники и помещаются в каталог исходных файлов репозитория в подкаталоги, соответствующие расширениям этих файлов. Например, внешний отчет ВнешнийОтчет1.erf будет разложен в каталог `src\erf`\ВнешнийОтчет1.

Есть ли возможность указать другой каталог назначения отличный от `src\erf...`?

**Comment by theshadowco** [comment]
На данный момент нет. Нужно?

**Comment by Live-AG** [comment]
Не критично конечно, просто хотелось бы разнести по разным репозиториям. Либо это как-то иначе можно организовать?

**Comment by theshadowco** [comment]
Не совсем понял, что значит "Разнести по разным репозиториям". 

Прекоммита у вас работает в конкретном репозитории, в котором у вас есть эти самые обработки, которые раскладываются в файлики. 

Опишите, что хотелось бы получить на выходе?

**Comment by Live-AG** [comment]
Да, все так. После того как Прекоммит разбирает обработки, он кладет результат в тот же репозиторий. Там надо настраивать gitignrore на каталог src получается. И мне кажется было бы удобней результат класть в отдельный репозиторий и там уже их проверять Сонаркубом.
А вообще я с Gitом и OScriptом только начинаю разбираться и вероятно чего-то не допонимаю.

**Comment by theshadowco** [comment]
хм...
Обработки находятся в репозитории, значит они его часть. Исходники этих обработок - то, что и должно в итоге быть самым главным в репозитории ). Зачем класть в другой реп мне не понятно. 
Есть желание визитеть обработки в отдельном проекте сонара? Если да, есть 2 пути
1. для обработок использовать другой репозиторий и на него настроить отдельный проект сонара
2. настроить конфигурацию сонара, сделав отдельный конфиг для каждого каталога, который хочется иметь отдельным проектом

Я в своей практике подобное не использую - все что есть в репе относится к одному проекту и анализируется вместе.

**Comment by Live-AG** [comment]
Спасибо, буду пробовать.
