### ISSUE TITLE
Работа сценария "ПроверкаКорректностиИнструкцийПрепроцессора"

### ISSUE THREAD

**Issue by Live-AG** [bia-technologies/precommit4onec#12]
При проверке, сценарий **ПроверкаКорректностиИнструкцийПрепроцессора** ругается на правильный код:
## Сообщение об ошибке:
```
12.08.2021 8:57:09: ИНФОРМАЦИЯ - Обработка файла 'C:\Git\Repository\ExternalsAnalisys\src\epf\Диадок Про\КонтурЭДО\Forms\НастройкаХраненияДанныхУправляемая\Ext\Form\Module.bsl' по сценарию 'ПроверкаКорректностиИнструкцийПрепроцессора'
12.08.2021 8:57:09: ОШИБКА - 'C:\Git\Repository\ExternalsAnalisys\src\epf\Диадок Про\КонтурЭДО\Forms\НастройкаХраненияДанныхУправляемая\Ext\Form\Module.bsl'
ошибка в написании инструкции 'Иначе    ' стр. '34'
12.08.2021 8:57:09: КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\precommit4onec\src\СценарииОбработки\ПроверкаКорректностиИнструкцийПрепроцессора.os / Ошибка в строке: 123 / 'C:\Git\Repository\ExternalsAnalisys\src\epf\Диадок Про\КонтурЭДО\Forms\НастройкаХраненияДанныхУправляемая\Ext\Form\Module.bsl' ошибка
в написании инструкции 'Иначе   ' стр. '34'}
                                ВызватьИсключение ТекстОшибки;
```
## сам код:
*стр. 34, это строка с `#Иначе`*
`
Процедура СохранитьКонфигурациюВФайл(Команда)
	
	#Если ВебКлиент Тогда
		
		Адрес = ПоместитьВоВременноеХранилище(ПолучитьМакетДляОбновленияДляХраненияДанных(), УникальныйИдентификатор);
		ПолучитьФайл(Адрес, "Диадок_upd.cf", Истина);
			
	#Иначе	
	
		ДиалогВыбора = Новый ДиалогВыбораФайла(РежимДиалогаВыбораФайла.Сохранение);
		ДиалогВыбора.Заголовок		= "Укажите файл, в который нужно сохранить обновление для вашей конфигурации";
		ДиалогВыбора.Фильтр			= "Файл конфигурации 1С (*.cf)|*.cf";      
		ДиалогВыбора.ПолноеИмяФайла = "Диадок_upd.cf";
		
		Если НЕ ДиалогВыбора.Выбрать() Тогда
			Возврат;
		КонецЕсли;
		
		ПутьКФайлу = ДиалогВыбора.ПолноеИмяФайла;
			
		ПолучитьМакетДляОбновленияДляХраненияДанных().Записать(ПутьКФайлу);
		
	#КонецЕсли
	
	ОписаниеОповещения = ОсновнаяФорма().НовыйОписаниеОповещения("ОбработчикЗакрытияФормы", ЭтаФорма);
	ОсновнаяФорма().ПоказатьПредупреждениеПереопределенная(ОписаниеОповещения,
	"ВНИМАНИЕ! 
	|При обновлении конфигурации в окне ""Сравнение, объединение"" НЕ ЗАБУДЬТЕ снять флажок с раздела ""Свойства""!
	|Запустите модуль после обновления конфигурации базы из файла.");
			
КонецПроцедуры
`

**Comment by theshadowco** [comment]
Версия используется последняя?

**Comment by Live-AG** [comment]
Да, последняя: 21.05.01

**Comment by theshadowco** [comment]
посмотрим, пока отключи этот сценарий в настройках

**Comment by theshadowco** [comment]
Исправлено в релизе 21.09
