### ISSUE TITLE
Корректировка XML форм. Не учитываются особенности

### ISSUE THREAD

**Issue by PerlAmutor** [bia-technologies/precommit4onec#13]
В скрипте КорректировкаXMLФорм.os не учитывается ряд особенностей.
Структура формы делится на три основных блока, каждый из которых имеет собственный subset id:
**ChildItems** - элементы формы
**Attributes** - реквизиты формы
**Commands** - команды формы

В этих трех блоках id элементов могут пересекаться и это нормально. Кроме того у каждого реквизита  (Attributes) с типом ТаблицаЗначений/ДеревоЗначений  может быть свой набор колонок с собственным subset id, а также вложенные таблицы значений в самой колонке другой таблицы значений, id которых также могут пересекаться.

![image](https://user-images.githubusercontent.com/87958986/146724935-bbc4cc1f-1a48-472f-ad95-8d119d46696a.png)

Сквозная перенумерация всех id форм это легкое и простое решение (naive approach), которое может породить в будущем множество новых конфликтов при переходе на следующий релиз. Хотелось бы видеть более умную (выборочную) перенумерацию, затрагивающую не все элементы XML, а лишь подмножества, где наблюдаются дубли.
Кроме того было бы неплохо иметь опцию, которая позволила бы не исправлять типовые формы конфигураций в которых не было изменений относительно текущей конфигурации и новой конфигурации поставщика (отдать на откуп разработчикам типовых конфигураций для избежания будущих конфликтов при объединении со следующим релизом). Для этого в качестве опционального параметра можно было бы передавать hash коммита с выгруженной конфигурацией поставщика, откуда тянуть файл типовой версии для последующего сравнения в скрипте.

Это пример того, сколько бы форм изменилось, если использовать эту обработку. Конфигурация - ERP. Количество строк равно количеству форм:

![image](https://user-images.githubusercontent.com/87958986/146727526-cd16e124-abe9-4b35-a682-7655196fc28b.png)

Кроме того иногда исправлять нужно не id формы, а ошибки объединения через гит. Вот пример:

![image](https://user-images.githubusercontent.com/87958986/147104687-a2a7e476-7d85-443f-b24f-ea22752bdcbb.png)

В данном случае безусловное исправление идентификаторов лишь заметает проблему под ковер.

Подкину пару идей. Необходимо проверять имена Элементов, Атрибутов и Команд на уникальность. Платформа по какой-то причине не выдает ошибок при загрузке форм из XML файлов, если в одном из трех блоков имена не уникальны и загружает все как есть. Расширенная проверка также не находит ошибки в этих формах. Такие ошибки необходимо исправлять двумя методами: ручным или автоматическим, через удаление лишнего.

https://user-images.githubusercontent.com/87958986/147381951-ee1016c4-5409-46a3-974e-3f67798a5505.mp4

Это просто примеры того как ведет себя платформа в Конфигураторе и рантайме, если есть дубли.

https://user-images.githubusercontent.com/87958986/147382012-c8d51a0d-4b64-413e-a2b4-165815387e4b.mp4

https://user-images.githubusercontent.com/87958986/147381999-4586b470-48ce-45ef-9256-3b9a4384b171.mp4

**Comment by theshadowco** [comment]
В версии 24.05 реализовано
