### ISSUE TITLE
Выпустить новую версию в oscript-library

### ISSUE THREAD

**Issue by realMaxA** [bia-technologies/precommit4onec#20]
Некогда был выполнен PR https://github.com/bia-technologies/precommit4onec/pull/18
Было бы неплохо иметь его в oscript-library, чтобы не было необходимости держать свою локальную версию данного инструмента.

**Comment by realMaxA** [comment]
Очень хочется прекоммита через серверную базу в релизе. Аж зубы сводит!

**Comment by theshadowco** [comment]
:) Постараюсь на днях

**Comment by theshadowco** [comment]
готово

**Comment by realMaxA** [comment]
В oscript-library эти изменения сами не попадут?
Тут https://github.com/oscript-library/precommit4onec старая версия.

**Comment by theshadowco** [comment]
а смысл поддерживать этот репозиторий? в хабе есть, здесь исходник лежит...

**Comment by realMaxA** [comment]
Хм, почему-то я считал, что пакеты в хаб собираются из репо из oscript-library.
Тогда мне надо ещё осознать, что есть оскрипт-хаб, есть разбросанные по просторам гитхаба репо-исходники, из которых собираются пакеты для оскрипт-хаба, и есть совершенно оторванный от жизни и неактуальный, в общем случае, oscript-library.
Благодарю.
