### ISSUE TITLE
Ошибка превышения длины пути файла 260 символов

### ISSUE THREAD

**Issue by puretruth** [bia-technologies/precommit4onec#25]
Словил ошибку при разборе обработок.
Срабатывает ограничение windows на длину пути 260 символов.
Нашёл в oscript аналогичную [ишью 67](https://github.com/EvilBeaver/OneScript/issues/67). Написано, что исправили, но как исправили - не понял. 
В соседнем [ишью 154](https://github.com/EvilBeaver/OneScript/issues/154) порекомендовали использовать v83unpack

Перемещение репозитория в корень диска не поможет, т.к. путь выгрузки по имени обработки в сумме с именем макета/формы получается более 260 символов.
На всякий случай. Настройку гита для использования длинных путей выполнил:
git config --system core.longpaths true

Ошибка выглядит так:
`КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\precommit4onec\src\СценарииОбработки\РазборОтчетовОбработокРасширений.os / Ошибка в строке: 103 / Внешнее исключение (System.IO.DirectoryNotFoundException): Не удалось найти часть пути "D:\repos\temp\test_ext_repo\src\epf\ПриказОПредоставленииНерабочегоВремениССохранениемСреднегоЗаработка\АК_ПриказОПредоставленииНерабочегоВремениССохранениемСреднегоЗаработка\Templates\ПриказОПредоставленииНерабочегоВремениССохранениемСреднегоЗаработка\Ext\Template.xml".}`

**Comment by theshadowco** [comment]
можно попробовать использовать более новый оскрипт. 

Лучше конечно что-то с именами решить, т.к. на уровне скрипта, увы, ничего не сделать

**Comment by puretruth** [comment]
> можно попробовать использовать более новый оскрипт.

Поспрашивал в сообществе OneScript - там тоже порекомендовали использовать версию движка 2.0.
В итоге сделал свой скрипт выгрузки.
