### ISSUE TITLE
git quotepath

### ISSUE THREAD

**Issue by IT-Medved** [bia-technologies/precommit4onec#26]
В случаях когда quotepath задан в true  или не задан вообще пути будут вида configuration/src/CommonModules/\320\240\320\260\320\271/Module.bsl
В самом прекоммите ничего не ломается, но проверка на файл существует выдает false.

Стоит либо предупредить пользователя либо найти способ превращать такие пути в нормальные

**Comment by theshadowco** [comment]
реализовано при установке прекоммита в репозиторий
