### ISSUE TITLE
Сборка проекта из исходников

### ISSUE THREAD

**Issue by HaSHsss** [bia-technologies/precommit4onec#29]
Нужен скрипт сборки внешних обработок из исходников. 

Мы работаем с внешней обработкой в которой есть и Управляемые и Обычные формы.

_Что делаю_
- РазборОбычныхФормНаИсходники
- РазборОтчетовОбработокРасширений

Хочу после выполнения Pull автоматически пересобирать Обработки epf
Планирую назначить Хук после Pull 

Я как понял мне нужно использовать v8unpuck -b (build)
из сложностей  пере сборка Form.bin из module.bsl (файлы обычных форм)
Тогда Form.bin можно добавить в ГитИгнор и получить красивый чисты коммит. Также заработает мердж веток для обычных форм.

Прошу дать мне направление 
Не может быть что я первый столкнулся с такой задачей

https://github.com/bia-technologies/precommit4onec/blob/bf94166f4d0e6357938a86a8efe1d443141ed6bd/tests/fixtures/%D0%A5%D1%80%D0%B0%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%D0%A0%D0%B0%D0%B7%D0%BD%D1%8B%D1%85%D0%9D%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B5%D0%BA/v8config.json#L31

В v8config.json нашел параметр Автосборка. Может это то что мне нужно?

**Comment by IT-Medved** [comment]
Привет!
Скорее всего вам нужен post-merge хук. Подобной функциональности нет в pre-commit.

Параметр АвтоСборка относится к нашему CI и не обрабатывается инструментом precommit4onec.

В целом ваша задача сводится к 
1. написанию os скрипта oscript с вызовом нужным вам действий. 
2. отладка скрипта
3. размещения его в репозитории решения ( есть и другие варианты)
4. редактирования post-merge хука на примере pre-commit хука в локальном репозитории
