### ISSUE TITLE
При 'СинхронизацияОбъектовМетаданныхИФайлов' не обрабатываются имена объектов метаданных содержащих "ё" в наименовании

### ISSUE THREAD

**Issue by anklimashenko** [bia-technologies/precommit4onec#31]
РегулярныеВыражения.ПолучитьДочерниеЭлементыОписанияКонфигурации(СодержимоеФайла, ЭтоEDT);

В этой функции правильное выражение будет:
РегекспМетаданные = Создать("^\s+<([\w]+)>([а-яёa-zA-ZА-ЯЁ0-9_]+)<\/[\w]+>");

**Comment by IT-Medved** [comment]
По стандарту там нельзя использовать букву ё https://its.1c.ru/db/v8std/content/474/hdoc
4. В именах, синонимах и комментариях не допускается использовать букву "ё".

**Comment by anklimashenko** [comment]
Да, спасибо - знаю. Но в типовом ДО например есть картинка с названием "Шестерёнка" и на ней проверка падает. Напишу в 1С чтобы не нарушали свои стандарты ) В целом можно закрыть issue, я у себя локально поправил строку с регулярками

**Comment by IT-Medved** [comment]
@anklimashenko, Ну, раз даже 1С так делает тогда точно стоит реализовать)) Спасибо что подсказал пример, стало понятнее. Опубликуем это исправление

**Comment by theshadowco** [comment]
В релиз 24.03
