### ISSUE TITLE
Внимание! Необходимо отключить сценарии УдалениеЛишнихКонцевыхПробелов и УдалениеЛишнихПустыхСтрок

### ISSUE THREAD

**Issue by Kirill** [bia-technologies/precommit4onec#40]
При использовании расширений и конструкций ИзменениеИКонтроль необходимо отключить данные сценарии, т.к. они меняют строки без учета контроля исходного кода основной конфигурации.

**Comment by Kirill** [comment]
Считаю ошибку очень критичной. Необходимо доработать замену, если она не включена в процедуры и функции с инструкцией ИзменениеИКонтроль, максимум только в блоке Вставка

**Comment by theshadowco** [comment]
Возьмем в следующий спринт

**Comment by theshadowco** [comment]
в релиз 24.11
