### ISSUE TITLE
Странное поведение при добавлении общих форм

### ISSUE THREAD

**Issue by GEDLordKim** [bia-technologies/precommit4onec#41]
Сообщение от процесса

КРИТИЧНАЯОШИБКА - {Модуль /root/.local/share/ovm/stable/lib/gitsync/oscript_modules/gitrunner/src/ГитРепозиторий.os / Ошибка в строке: 172 / precommit4onec v24.05
ИНФОРМАЦИЯ - Используем локальные настройки
ИНФОРМАЦИЯ - Читаем настройки 
ИНФОРМАЦИЯ - Обработка файла '/home/jenkins/agent/workspace/depot_git_sync/src/cf/CommonForms/.../Ext/Form.xml' по сценарию 'КорректировкаXMLФорм'
КРИТИЧНАЯОШИБКА - {Модуль /root/.local/share/ovm/stable/lib/precommit4onec/src/Классы/ДанныеФормы.os / Ошибка в строке: 314 / Неверное значение аргумента}    
ПоследнийИдентификатор = ТаблицаИдентификаторов[ТаблицаИдентификаторов.Количество() - 1].НовыйИдентификатор;
}

Есть подозрение, что отсутствует проверка на количество записей в ТаблицаИдентификаторов
![Untitled](https://github.com/user-attachments/assets/31a5db14-2bc0-43ba-ac4a-538698a2cf7c)

**Comment by theshadowco** [comment]
в релизе 24.11
