### ISSUE TITLE
РазборОтчетовОбработокРасширений - критичная ошибка

### ISSUE THREAD

**Issue by john91687** [bia-technologies/precommit4onec#8]
КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\precommit4onec\src\Классы\КомандаВыполнитьСценарии.os / Ошибка в строке: 96 / Внешнее исключение (System.IO.FileNotFoundException): Файл 'c:\temp\Repo\upp_test\.g
it\hooks\tools\src\АЗС\Forms\ФормаВыбора\Ext\Form\Module.bsl' не найден.}
Если АнализируемыйФайл.ЭтоКаталог() Тогда

Это возникает при запуске разбора обычной формы с расширением *.bin. Непонятно, что он от Module.bsl хочет - пустышку создавал такую - не помогло. Сам бинарный файл получен путем выгрузки файлов конфигурации УПП 1.3 в иерархическую структуру

**Comment by theshadowco** [comment]
а какой каталог вы указали при настройке прекоммита?
судя по этой части `c:\temp\Repo\upp_test.git\hooks\` что-то у вас с настройками не так

**Comment by theshadowco** [comment]
@john91687
